### ISSUE TITLE
would you like to collaborate to create a blockchain video game

### ISSUE THREAD

**Issue by stevenstc** [Raptor007/BTTT#1]
Hello, I am a developer in the tron network, I was wondering if you are interested in creating a video game to implement it in the blockchain, I would like you to contact me if you are interested, I am very encouraged, successes in what you do

**Comment by Raptor007** [comment]
Sorry, I think the short answer is no.  I work on these projects in my spare time, but I also have a day job and family life.  I don't think I could commit enough time to another new project to be an effective collaborator.

Also, I have not coded anything for blockchain, but my layman's understanding is that it provides a distributed permanent ledger that acts as a sort of decentralized append-only database, at the expense of high bandwidth use and long transaction delay.  When I think of video games, where responsiveness is often measured in milliseconds, this doesn't seem like the right tool for the job.

(Feel free to continue the conversation here, but I am closing this issue as it is not a BTTT bug.)
